name: Merge
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun test:ci
      - name: Download codecov
        run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
      - name: Run codecov
        run: ./codecov
